services:
  - type: web
    name: monar
    runtime: node
    buildCommand: npm install --include=dev && npm run build:all
    startCommand: npm run seed && npx tsx server/server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
