/**
 * Seed menu categories and dishes for the demo restaurant.
 * Run with: npx tsx server/scripts/seedMenu.ts
 */
import '../config/env';
import mongoose from 'mongoose';
import { env } from '../config/env';
import { Restaurant } from '../models/Restaurant';
import { Category } from '../models/Category';
import { MenuItem } from '../models/MenuItem';

const CATEGORIES = [
  { name: 'Appetizers',          description: 'Light starters to begin your meal' },
  { name: 'Salads',              description: 'Fresh garden and specialty salads' },
  { name: 'Soups',               description: 'Comforting hot soups made fresh daily' },
  { name: 'Main Course',         description: 'Hearty and satisfying main dishes' },
  { name: 'Pasta & Risotto',     description: 'Italian-inspired pasta and creamy risotto' },
  { name: 'Burgers & Sandwiches',description: 'Handcrafted burgers and gourmet sandwiches' },
  { name: 'Pizza',               description: 'Stone-baked pizzas with premium toppings' },
  { name: 'Seafood',             description: 'Fresh catch of the day and ocean classics' },
  { name: 'Desserts',            description: 'Sweet endings to a perfect meal' },
  { name: 'Beverages',           description: 'Refreshing drinks, hot and cold' },
];

const MENU_ITEMS = [
  // ─── APPETIZERS ────────────────────────────────────────────────────────────
  {
    name: 'Crispy Calamari',
    category: 'Appetizers',
    price: 12.99,
    description: 'Golden-fried squid rings with house marinara',
    longDescription: 'Tender squid rings lightly breaded and fried to perfection. Served with our house-made marinara sauce, a zesty garlic aioli, and a fresh lemon wedge.',
    ingredients: ['Squid', 'Breadcrumbs', 'Flour', 'Egg', 'Olive oil', 'Garlic', 'Lemon', 'Parsley'],
    allergens: ['Gluten', 'Egg', 'Seafood'],
    image: '/uploads/menu-calamari.jpg',
    featured: true,
  },
  {
    name: 'Bruschetta al Pomodoro',
    category: 'Appetizers',
    price: 9.50,
    description: 'Toasted sourdough with fresh tomatoes, basil and olive oil',
    longDescription: 'Classic Italian bruschetta on thick-cut grilled sourdough, topped with diced ripe tomatoes, garlic, fresh basil and a generous drizzle of extra virgin olive oil. Finished with a pinch of sea salt.',
    ingredients: ['Sourdough bread', 'Tomatoes', 'Basil', 'Garlic', 'Olive oil', 'Sea salt', 'Balsamic glaze'],
    allergens: ['Gluten'],
    image: '/uploads/menu-bruschetta.jpg',
    featured: false,
  },
  {
    name: 'Spinach & Artichoke Dip',
    category: 'Appetizers',
    price: 11.00,
    description: 'Warm creamy dip served with tortilla chips and pita',
    longDescription: 'A warm, bubbling blend of wilted spinach, artichoke hearts, cream cheese and melted mozzarella, baked until golden. Served with a basket of tortilla chips and warm pita wedges.',
    ingredients: ['Spinach', 'Artichoke hearts', 'Cream cheese', 'Parmesan', 'Mozzarella', 'Garlic', 'Sour cream'],
    allergens: ['Dairy', 'Gluten'],
    image: '/uploads/menu-spinach-dip.jpg',
    featured: false,
  },
  {
    name: 'Chicken Wings (1 lb)',
    category: 'Appetizers',
    price: 14.99,
    description: 'Crispy wings with your choice of Buffalo, BBQ or Honey Garlic',
    longDescription: 'A full pound of crispy double-fried chicken wings tossed in your choice of Buffalo hot sauce, smoky BBQ, or sweet honey garlic glaze. Served with celery sticks, carrot batons and blue cheese dip.',
    ingredients: ['Chicken wings', 'Hot sauce', 'Butter', 'Garlic', 'Honey', 'Celery', 'Carrots', 'Blue cheese'],
    allergens: ['Dairy'],
    image: '/uploads/menu-chicken-wings.jpg',
    featured: true,
  },
  {
    name: 'Shrimp Cocktail',
    category: 'Appetizers',
    price: 16.50,
    description: 'Chilled jumbo shrimp with zesty cocktail sauce and lemon',
    longDescription: 'Six chilled jumbo shrimp poached in a seasoned court bouillon, arranged on crushed ice with our house-made cocktail sauce, horseradish cream and fresh lemon wedges.',
    ingredients: ['Jumbo shrimp', 'Cocktail sauce', 'Horseradish', 'Lemon', 'Celery salt', 'Old Bay'],
    allergens: ['Seafood'],
    image: '/uploads/menu-calamari.jpg',
    featured: false,
  },
  {
    name: 'Stuffed Mushrooms',
    category: 'Appetizers',
    price: 10.50,
    description: 'Portobello caps filled with herbed ricotta and sun-dried tomatoes',
    longDescription: 'Meaty portobello mushroom caps stuffed with a savory mixture of ricotta, spinach, sun-dried tomatoes, garlic and parmesan, baked until golden and finished with a balsamic reduction.',
    ingredients: ['Portobello mushrooms', 'Ricotta', 'Spinach', 'Sun-dried tomatoes', 'Parmesan', 'Garlic', 'Thyme'],
    allergens: ['Dairy'],
    image: '/uploads/menu-spinach-dip.jpg',
    featured: false,
  },
  {
    name: 'Nachos Grande',
    category: 'Appetizers',
    price: 13.50,
    description: 'Loaded tortilla chips with cheese, jalapeños, guac and sour cream',
    longDescription: 'A generous mountain of crispy tortilla chips layered with melted cheddar jack cheese, seasoned ground beef, pickled jalapeños, pico de gallo, guacamole and sour cream.',
    ingredients: ['Tortilla chips', 'Cheddar jack', 'Ground beef', 'Jalapeños', 'Tomatoes', 'Onion', 'Guacamole', 'Sour cream'],
    allergens: ['Dairy', 'Gluten'],
    image: '/uploads/menu-spinach-dip.jpg',
    featured: false,
  },

  // ─── SALADS ────────────────────────────────────────────────────────────────
  {
    name: 'Classic Caesar Salad',
    category: 'Salads',
    price: 13.50,
    description: 'Romaine, house-made Caesar dressing, parmesan and croutons',
    longDescription: 'Crisp romaine hearts tossed with our house-made anchovy Caesar dressing, shaved aged parmesan and golden herb croutons. Add grilled chicken +$4, grilled shrimp +$6.',
    ingredients: ['Romaine lettuce', 'Parmesan', 'Croutons', 'Caesar dressing', 'Lemon', 'Anchovies', 'Garlic'],
    allergens: ['Dairy', 'Gluten', 'Egg', 'Fish'],
    image: '/uploads/menu-caesar-salad.jpg',
    featured: false,
  },
  {
    name: 'Greek Salad',
    category: 'Salads',
    price: 12.50,
    description: 'Tomatoes, cucumber, olives, red onion and feta in herb dressing',
    longDescription: 'A classic Greek village salad with ripe tomatoes, crisp cucumber, Kalamata olives, red onion and generous crumbles of authentic feta cheese, dressed with dried oregano and extra virgin olive oil.',
    ingredients: ['Tomatoes', 'Cucumber', 'Kalamata olives', 'Red onion', 'Feta cheese', 'Olive oil', 'Oregano', 'Red wine vinegar'],
    allergens: ['Dairy'],
    image: '/uploads/menu-greek-salad.jpg',
    featured: false,
  },
  {
    name: 'Grilled Chicken Salad',
    category: 'Salads',
    price: 15.99,
    description: 'Mixed greens with grilled chicken, avocado, almonds and honey-mustard',
    longDescription: 'A generous bowl of mixed baby greens topped with sliced grilled chicken breast, creamy avocado, cherry tomatoes, candied walnuts and shaved parmesan, finished with our house honey-mustard vinaigrette.',
    ingredients: ['Mixed greens', 'Chicken breast', 'Avocado', 'Cherry tomatoes', 'Candied walnuts', 'Parmesan', 'Honey-mustard dressing'],
    allergens: ['Nuts', 'Dairy', 'Mustard'],
    image: '/uploads/menu-chicken-salad.jpg',
    featured: true,
  },
  {
    name: 'Caprese Salad',
    category: 'Salads',
    price: 14.00,
    description: 'Fresh mozzarella, heirloom tomatoes, basil and balsamic glaze',
    longDescription: 'Thick slices of fresh buffalo mozzarella layered with ripe heirloom tomatoes, fragrant basil leaves and a sweet balsamic reduction, drizzled with premium extra virgin olive oil and flaked sea salt.',
    ingredients: ['Buffalo mozzarella', 'Heirloom tomatoes', 'Basil', 'Olive oil', 'Balsamic reduction', 'Sea salt', 'Black pepper'],
    allergens: ['Dairy'],
    image: '/uploads/menu-greek-salad.jpg',
    featured: false,
  },
  {
    name: 'Quinoa Power Bowl',
    category: 'Salads',
    price: 14.50,
    description: 'Quinoa, roasted veggies, chickpeas, avocado and tahini dressing',
    longDescription: 'A nourishing bowl of fluffy tri-color quinoa topped with roasted sweet potato, chickpeas, sliced avocado, cucumber, cherry tomatoes and a drizzle of creamy tahini-lemon dressing.',
    ingredients: ['Quinoa', 'Sweet potato', 'Chickpeas', 'Avocado', 'Cucumber', 'Cherry tomatoes', 'Tahini', 'Lemon'],
    allergens: ['Sesame', 'Nuts'],
    image: '/uploads/menu-chicken-salad.jpg',
    featured: false,
  },
  {
    name: 'Arugula & Prosciutto Salad',
    category: 'Salads',
    price: 15.50,
    description: 'Peppery arugula with prosciutto, pear, gorgonzola and candied walnuts',
    longDescription: 'A sophisticated salad of peppery wild arugula tossed with thin slices of San Daniele prosciutto, sliced ripe pear, crumbled gorgonzola and candied walnuts, with a light white wine vinaigrette.',
    ingredients: ['Arugula', 'Prosciutto', 'Pear', 'Gorgonzola', 'Candied walnuts', 'White wine vinaigrette'],
    allergens: ['Dairy', 'Nuts'],
    image: '/uploads/menu-caesar-salad.jpg',
    featured: false,
  },

  // ─── SOUPS ─────────────────────────────────────────────────────────────────
  {
    name: 'French Onion Soup',
    category: 'Soups',
    price: 10.99,
    description: 'Caramelized onion broth topped with gruyère crouton',
    longDescription: 'A deeply rich broth of slow-caramelized onions in beef consommé, ladled into a crock and topped with a thick toasted crouton and a gratinéed blanket of melted Gruyère cheese.',
    ingredients: ['Yellow onion', 'Beef broth', 'Dry white wine', 'Thyme', 'Bay leaf', 'Gruyère', 'Baguette', 'Butter'],
    allergens: ['Dairy', 'Gluten'],
    image: '/uploads/menu-chicken-wings.jpg',
    featured: true,
  },
  {
    name: 'Tomato Basil Bisque',
    category: 'Soups',
    price: 9.50,
    description: 'Velvety roasted tomato soup with fresh cream and basil oil',
    longDescription: 'A smooth, velvety bisque of oven-roasted plum tomatoes blended with vegetable stock, finished with a swirl of heavy cream and aromatic basil oil. Served with a warm sourdough roll.',
    ingredients: ['Plum tomatoes', 'Vegetable stock', 'Heavy cream', 'Basil', 'Garlic', 'Onion', 'Olive oil'],
    allergens: ['Dairy', 'Gluten'],
    image: '/uploads/menu-bruschetta.jpg',
    featured: false,
  },
  {
    name: 'Clam Chowder',
    category: 'Soups',
    price: 11.50,
    description: 'New England-style creamy chowder with clams and potatoes',
    longDescription: 'Thick and creamy New England clam chowder made with fresh clams, diced potatoes, smoky bacon and aromatic celery, topped with oyster crackers and fresh chives.',
    ingredients: ['Clams', 'Potatoes', 'Bacon', 'Heavy cream', 'Celery', 'Onion', 'Thyme', 'Oyster crackers'],
    allergens: ['Dairy', 'Gluten', 'Seafood'],
    image: '/uploads/menu-salmon.jpg',
    featured: false,
  },
  {
    name: 'Lentil & Vegetable Soup',
    category: 'Soups',
    price: 8.99,
    description: 'Hearty red lentil soup with cumin, carrots and fresh herbs',
    longDescription: 'A warming, protein-rich soup of red lentils simmered with carrots, celery, tomatoes, cumin and smoked paprika, finished with a squeeze of lemon and a drizzle of olive oil. Vegan-friendly.',
    ingredients: ['Red lentils', 'Carrots', 'Celery', 'Tomatoes', 'Cumin', 'Smoked paprika', 'Lemon', 'Olive oil'],
    allergens: [],
    image: '/uploads/menu-stir-fry.jpg',
    featured: false,
  },

  // ─── MAIN COURSE ───────────────────────────────────────────────────────────
  {
    name: 'Grilled Atlantic Salmon',
    category: 'Main Course',
    price: 26.99,
    description: 'Pan-seared salmon with lemon-caper butter and wild rice',
    longDescription: 'A 7oz Atlantic salmon fillet pan-seared to medium and finished with a lemon-caper beurre blanc, served on a bed of herb wild rice with broccolini and charred lemon.',
    ingredients: ['Salmon fillet', 'Lemon', 'Capers', 'Butter', 'Wild rice', 'Broccolini', 'Dill', 'White wine'],
    allergens: ['Fish', 'Dairy'],
    image: '/uploads/menu-salmon.jpg',
    featured: true,
  },
  {
    name: '12oz Ribeye Steak',
    category: 'Main Course',
    price: 38.00,
    description: 'USDA prime ribeye with garlic mashed potatoes and red wine jus',
    longDescription: 'A prime 12oz bone-in ribeye, cooked to your preferred temperature and rested perfectly. Served with silky garlic mashed potatoes, roasted asparagus and a rich red wine and rosemary reduction.',
    ingredients: ['Ribeye steak', 'Garlic', 'Rosemary', 'Butter', 'Yukon Gold potatoes', 'Cream', 'Asparagus', 'Cabernet'],
    allergens: ['Dairy'],
    image: '/uploads/menu-ribeye.jpg',
    featured: true,
  },
  {
    name: 'Chicken Parmigiana',
    category: 'Main Course',
    price: 21.99,
    description: 'Breaded chicken breast baked with marinara and melted mozzarella',
    longDescription: 'A golden panko-crusted chicken breast baked in rich San Marzano marinara with melted mozzarella and parmesan, served alongside spaghetti tossed in garlic-olive oil and fresh basil.',
    ingredients: ['Chicken breast', 'Panko breadcrumbs', 'San Marzano tomatoes', 'Mozzarella', 'Spaghetti', 'Parmesan', 'Basil'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-chicken-parm.jpg',
    featured: false,
  },
  {
    name: 'Vegetable Stir-Fry',
    category: 'Main Course',
    price: 17.50,
    description: 'Seasonal vegetables in ginger-soy glaze over jasmine rice',
    longDescription: 'A vibrant medley of fresh-market vegetables — broccoli, snap peas, bell peppers, mushrooms and baby corn — wok-tossed in a ginger-soy-sesame glaze. Served over steamed jasmine rice with sesame seeds and scallions.',
    ingredients: ['Broccoli', 'Snap peas', 'Bell peppers', 'Mushrooms', 'Baby corn', 'Ginger', 'Soy sauce', 'Sesame oil', 'Jasmine rice'],
    allergens: ['Soy', 'Sesame'],
    image: '/uploads/menu-stir-fry.jpg',
    featured: false,
  },
  {
    name: 'Lamb Chops',
    category: 'Main Course',
    price: 34.00,
    description: 'Herb-crusted rack of lamb with roasted garlic and mint sauce',
    longDescription: 'Two French-trimmed lamb chops crusted with Dijon, rosemary and breadcrumbs, roasted to a blush-pink medium-rare. Served with roasted garlic potato gratin and a vibrant fresh mint sauce.',
    ingredients: ['Lamb chops', 'Dijon mustard', 'Rosemary', 'Breadcrumbs', 'Garlic', 'Potatoes', 'Cream', 'Mint', 'Red wine'],
    allergens: ['Gluten', 'Dairy', 'Mustard'],
    image: '/uploads/menu-ribeye.jpg',
    featured: true,
  },
  {
    name: 'Duck Confit',
    category: 'Main Course',
    price: 29.99,
    description: 'Slow-cooked duck leg with cherry sauce and pommes sarladaises',
    longDescription: 'A slow-cooked duck leg confit with crispy lacquered skin, served on a bed of pommes sarladaises (duck-fat potatoes with garlic and parsley) and a glossy morello cherry pan sauce.',
    ingredients: ['Duck leg', 'Duck fat', 'Potatoes', 'Garlic', 'Thyme', 'Bay leaf', 'Morello cherries', 'Port wine'],
    allergens: [],
    image: '/uploads/menu-ribeye.jpg',
    featured: false,
  },
  {
    name: 'Pork Tenderloin',
    category: 'Main Course',
    price: 24.99,
    description: 'Pan-roasted pork with apple-calvados sauce and roasted root veg',
    longDescription: 'A succulent pork tenderloin, seared golden and finished in the oven, served with a Calvados and Bramley apple reduction, honey-roasted root vegetables and creamy parsnip purée.',
    ingredients: ['Pork tenderloin', 'Apples', 'Calvados', 'Shallots', 'Parsnips', 'Carrots', 'Cream', 'Thyme'],
    allergens: ['Dairy'],
    image: '/uploads/menu-chicken-parm.jpg',
    featured: false,
  },

  // ─── PASTA & RISOTTO ───────────────────────────────────────────────────────
  {
    name: 'Spaghetti Carbonara',
    category: 'Pasta & Risotto',
    price: 18.50,
    description: 'Roman carbonara with pancetta, egg yolk and aged parmesan',
    longDescription: 'Authentic Roman carbonara: al dente spaghetti tossed in a silky emulsion of egg yolks, crispy guanciale, freshly cracked black pepper and Pecorino Romano. No cream — just the real thing.',
    ingredients: ['Spaghetti', 'Guanciale', 'Egg yolks', 'Pecorino Romano', 'Parmesan', 'Black pepper'],
    allergens: ['Gluten', 'Egg', 'Dairy'],
    image: '/uploads/menu-carbonara.jpg',
    featured: true,
  },
  {
    name: 'Penne Arrabbiata',
    category: 'Pasta & Risotto',
    price: 16.00,
    description: 'Spicy San Marzano tomato sauce with garlic and fresh chili',
    longDescription: 'Ridged penne in a fiery San Marzano tomato sauce bursting with garlic and fresh chili. Garnished with flat-leaf parsley and a dusting of Parmigiano Reggiano. A bold classic done right.',
    ingredients: ['Penne', 'San Marzano tomatoes', 'Garlic', 'Red chili', 'Olive oil', 'Parsley', 'Parmesan'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-arrabbiata.jpg',
    featured: false,
  },
  {
    name: 'Wild Mushroom Risotto',
    category: 'Pasta & Risotto',
    price: 19.99,
    description: 'Arborio rice with porcini, shiitake and truffle oil',
    longDescription: 'Slow-stirred Arborio rice cooked in rich porcini broth, folded with sautéed shiitake, cremini and oyster mushrooms, mascarpone and Grana Padano, finished with a luxurious drizzle of black truffle oil.',
    ingredients: ['Arborio rice', 'Porcini mushrooms', 'Shiitake', 'Oyster mushrooms', 'Vegetable stock', 'Mascarpone', 'Grana Padano', 'Truffle oil', 'White wine'],
    allergens: ['Dairy'],
    image: '/uploads/menu-risotto.jpg',
    featured: true,
  },
  {
    name: 'Seafood Linguine',
    category: 'Pasta & Risotto',
    price: 24.99,
    description: 'Linguine with clams, mussels, shrimp and cherry tomatoes in white wine',
    longDescription: 'Linguine tossed with fresh clams, mussels and prawns in a fragrant white wine, garlic and cherry tomato sauce with a hint of chili. Finished with flat-leaf parsley and a drizzle of top-quality olive oil.',
    ingredients: ['Linguine', 'Clams', 'Mussels', 'Prawns', 'Cherry tomatoes', 'White wine', 'Garlic', 'Chili', 'Parsley'],
    allergens: ['Gluten', 'Seafood'],
    image: '/uploads/menu-carbonara.jpg',
    featured: false,
  },
  {
    name: 'Lasagna Bolognese',
    category: 'Pasta & Risotto',
    price: 20.50,
    description: 'Layered pasta with slow-braised beef ragù and béchamel',
    longDescription: 'Layers of fresh egg lasagna sheets, a 4-hour slow-braised beef and pork Bolognese ragù, silky béchamel and generous gratings of Parmigiano Reggiano, baked until bubbling and golden-crusted.',
    ingredients: ['Lasagna sheets', 'Ground beef', 'Ground pork', 'Tomatoes', 'Béchamel', 'Parmesan', 'Onion', 'Celery', 'Carrot', 'Red wine'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-arrabbiata.jpg',
    featured: false,
  },
  {
    name: 'Gnocchi al Pesto',
    category: 'Pasta & Risotto',
    price: 17.50,
    description: 'Pillowy potato gnocchi with Genovese basil pesto and pine nuts',
    longDescription: 'Hand-rolled potato gnocchi dressed in a vibrant Genovese pesto made from fresh Ligurian basil, pine nuts, Parmigiano, Pecorino and extra virgin olive oil, topped with extra pine nuts and basil leaves.',
    ingredients: ['Potato gnocchi', 'Basil', 'Pine nuts', 'Parmesan', 'Pecorino', 'Olive oil', 'Garlic'],
    allergens: ['Gluten', 'Dairy', 'Nuts'],
    image: '/uploads/menu-risotto.jpg',
    featured: false,
  },

  // ─── BURGERS & SANDWICHES ──────────────────────────────────────────────────
  {
    name: 'Classic Smash Burger',
    category: 'Burgers & Sandwiches',
    price: 16.99,
    description: 'Double smash patty, American cheese, pickles and special sauce',
    longDescription: 'Two 3oz beef patties smashed crispy on the griddle, layered with melted American cheese, dill pickles, shredded lettuce, sliced tomato and our signature house sauce in a toasted brioche bun. Served with shoestring fries.',
    ingredients: ['Beef patty', 'American cheese', 'Brioche bun', 'Lettuce', 'Tomato', 'Pickles', 'Special sauce'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-cheeseburger.jpg',
    featured: true,
  },
  {
    name: 'BBQ Bacon Burger',
    category: 'Burgers & Sandwiches',
    price: 19.50,
    description: 'Double patty, smoked bacon, BBQ sauce and crispy onion rings',
    longDescription: 'Two beef patties stacked with crispy smoked streaky bacon, melted smoked gouda, tangy BBQ sauce and a tower of beer-battered onion rings on a toasted pretzel bun. Served with seasoned fries.',
    ingredients: ['Beef patties', 'Smoked bacon', 'Smoked gouda', 'BBQ sauce', 'Onion rings', 'Pretzel bun', 'Lettuce', 'Tomato'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-bbq-burger.jpg',
    featured: false,
  },
  {
    name: 'Grilled Chicken Sandwich',
    category: 'Burgers & Sandwiches',
    price: 15.50,
    description: 'Marinated chicken breast with avocado, Swiss and pesto aioli',
    longDescription: 'A lemon-herb marinated grilled chicken breast on toasted ciabatta with creamy avocado, melted Swiss cheese, roasted red peppers, baby spinach and pesto aioli.',
    ingredients: ['Chicken breast', 'Ciabatta', 'Avocado', 'Swiss cheese', 'Roasted peppers', 'Pesto aioli', 'Baby spinach'],
    allergens: ['Gluten', 'Dairy', 'Nuts'],
    image: '/uploads/menu-chicken-sandwich.jpg',
    featured: false,
  },
  {
    name: 'Veggie Burger',
    category: 'Burgers & Sandwiches',
    price: 15.99,
    description: 'Black bean and quinoa patty with avocado and chipotle mayo',
    longDescription: 'A hearty house-made black bean and quinoa patty seasoned with cumin and smoked paprika, served on a toasted sesame bun with fresh avocado, sliced tomato, crisp lettuce and smoky chipotle mayo.',
    ingredients: ['Black beans', 'Quinoa', 'Cumin', 'Smoked paprika', 'Sesame bun', 'Avocado', 'Tomato', 'Lettuce', 'Chipotle mayo'],
    allergens: ['Gluten', 'Egg', 'Sesame'],
    image: '/uploads/menu-cheeseburger.jpg',
    featured: false,
  },
  {
    name: 'Fish Burger',
    category: 'Burgers & Sandwiches',
    price: 17.50,
    description: 'Beer-battered cod fillet with tartare sauce and pickled slaw',
    longDescription: 'A chunky beer-battered cod fillet, crispy and flaky inside, on a toasted potato bun with house tartare sauce, tangy pickled cabbage slaw and a squeeze of lemon.',
    ingredients: ['Cod fillet', 'Beer batter', 'Potato bun', 'Tartare sauce', 'Red cabbage', 'Vinegar', 'Lemon'],
    allergens: ['Gluten', 'Fish', 'Dairy', 'Egg'],
    image: '/uploads/menu-chicken-sandwich.jpg',
    featured: false,
  },
  {
    name: 'Club Sandwich',
    category: 'Burgers & Sandwiches',
    price: 16.00,
    description: 'Triple-decker with turkey, bacon, egg, lettuce and tomato',
    longDescription: 'A towering triple-decker club on toasted white bread with sliced roast turkey, crispy bacon, fried egg, crisp lettuce, ripe tomato and Dijon mayo, served with a side of coleslaw and chips.',
    ingredients: ['White bread', 'Turkey', 'Bacon', 'Fried egg', 'Lettuce', 'Tomato', 'Dijon mayo'],
    allergens: ['Gluten', 'Dairy', 'Egg', 'Mustard'],
    image: '/uploads/menu-bbq-burger.jpg',
    featured: false,
  },

  // ─── PIZZA ─────────────────────────────────────────────────────────────────
  {
    name: 'Margherita',
    category: 'Pizza',
    price: 15.99,
    description: 'San Marzano tomato, fior di latte mozzarella and fresh basil',
    longDescription: 'Our Neapolitan-style pizza base hand-stretched and baked in a stone oven, topped with crushed San Marzano tomatoes, fior di latte mozzarella, a drizzle of olive oil and fresh basil leaves.',
    ingredients: ['Pizza dough', 'San Marzano tomatoes', 'Fior di latte', 'Basil', 'Olive oil', 'Sea salt'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-bruschetta.jpg',
    featured: false,
  },
  {
    name: 'Pepperoni Pizza',
    category: 'Pizza',
    price: 17.99,
    description: 'Loaded with cups-and-char pepperoni on a rich tomato base',
    longDescription: 'Generously topped with cupped pepperoni that crisps and chars at the edges, over a garlicky tomato sauce and stretchy mozzarella on our signature sourdough-blend dough.',
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Pepperoni', 'Garlic', 'Oregano'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-cheeseburger.jpg',
    featured: true,
  },
  {
    name: 'Truffle Mushroom Pizza',
    category: 'Pizza',
    price: 21.50,
    description: 'Wild mushrooms, taleggio, caramelized onions and truffle oil',
    longDescription: 'A white-base pizza with no tomato sauce — instead, velvety taleggio cheese, sautéed mixed wild mushrooms, slow caramelized onions, fresh thyme and a lavish drizzle of Italian truffle oil.',
    ingredients: ['Pizza dough', 'Taleggio', 'Mixed mushrooms', 'Caramelized onion', 'Thyme', 'Truffle oil'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-risotto.jpg',
    featured: false,
  },
  {
    name: 'BBQ Chicken Pizza',
    category: 'Pizza',
    price: 19.00,
    description: 'Smoky BBQ chicken, red onion, coriander and smoked mozzarella',
    longDescription: 'Pulled BBQ chicken, thinly sliced red onion, smoked mozzarella and a drizzle of smoky BBQ sauce on our stone-baked base, finished with fresh coriander.',
    ingredients: ['Pizza dough', 'BBQ sauce', 'Chicken breast', 'Red onion', 'Smoked mozzarella', 'Coriander'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-bbq-burger.jpg',
    featured: false,
  },
  {
    name: 'Quattro Stagioni',
    category: 'Pizza',
    price: 20.00,
    description: 'Four seasons pizza: artichoke, olives, mushrooms and ham',
    longDescription: 'Divided into four quarters — each representing a season — topped with marinated artichoke hearts, Kalamata olives, sautéed mushrooms and cooked ham over a rich tomato base with mozzarella.',
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Artichoke', 'Olives', 'Mushrooms', 'Ham'],
    allergens: ['Gluten', 'Dairy'],
    image: '/uploads/menu-arrabbiata.jpg',
    featured: false,
  },

  // ─── SEAFOOD ───────────────────────────────────────────────────────────────
  {
    name: 'Lobster Bisque',
    category: 'Seafood',
    price: 18.00,
    description: 'Creamy lobster bisque with cognac and a lobster claw garnish',
    longDescription: 'A luxuriously smooth bisque made from a roasted whole lobster shell stock, enriched with cream, a splash of Cognac and tarragon, served in a warm bowl with a butter-poached lobster claw and micro herbs.',
    ingredients: ['Lobster', 'Heavy cream', 'Cognac', 'Tarragon', 'Shallots', 'Tomato paste', 'Butter'],
    allergens: ['Dairy', 'Seafood'],
    image: '/uploads/menu-salmon.jpg',
    featured: true,
  },
  {
    name: 'Fish & Chips',
    category: 'Seafood',
    price: 19.50,
    description: 'Beer-battered haddock with chunky chips, mushy peas and tartare',
    longDescription: 'A generous fillet of sustainably sourced haddock in a light, crispy beer batter served alongside chunky hand-cut chips, proper mushy peas and our house-made dill tartare sauce.',
    ingredients: ['Haddock', 'Beer batter', 'Potatoes', 'Mushy peas', 'Tartare sauce', 'Lemon', 'Vinegar'],
    allergens: ['Gluten', 'Fish', 'Dairy', 'Egg'],
    image: '/uploads/menu-salmon.jpg',
    featured: false,
  },
  {
    name: 'Grilled Tiger Prawns',
    category: 'Seafood',
    price: 26.00,
    description: 'Six tiger prawns with garlic-chili butter and charred bread',
    longDescription: 'Six whole tiger prawns butterflied and grilled over charcoal, basted with a fragrant garlic-chili-herb butter. Served with thick-cut charred sourdough to soak up the juices and a wedge of lemon.',
    ingredients: ['Tiger prawns', 'Butter', 'Garlic', 'Chili', 'Parsley', 'Lemon', 'Sourdough'],
    allergens: ['Seafood', 'Dairy', 'Gluten'],
    image: '/uploads/menu-calamari.jpg',
    featured: false,
  },
  {
    name: 'Seafood Platter (for 2)',
    category: 'Seafood',
    price: 65.00,
    description: 'Lobster tail, tiger prawns, oysters, crab claws and smoked salmon',
    longDescription: 'A spectacular cold and hot seafood sharing board featuring half a grilled lobster tail, four tiger prawns, three fresh oysters, crab claws, smoked salmon ribbons and an array of sauces — mignonette, cocktail and aioli.',
    ingredients: ['Lobster', 'Tiger prawns', 'Oysters', 'Crab claws', 'Smoked salmon', 'Mignonette', 'Cocktail sauce', 'Aioli'],
    allergens: ['Seafood', 'Dairy', 'Egg'],
    image: '/uploads/menu-calamari.jpg',
    featured: true,
  },
  {
    name: 'Pan-Seared Sea Bass',
    category: 'Seafood',
    price: 28.99,
    description: 'Crispy skin sea bass with saffron cream, samphire and lemon',
    longDescription: 'A fillet of line-caught sea bass pan-seared to achieve a perfectly lacquered crispy skin, rested on a delicate saffron cream with samphire, braised fennel and a lemon butter sauce.',
    ingredients: ['Sea bass', 'Saffron', 'Heavy cream', 'Samphire', 'Fennel', 'Butter', 'Lemon', 'White wine'],
    allergens: ['Fish', 'Dairy'],
    image: '/uploads/menu-salmon.jpg',
    featured: false,
  },

  // ─── DESSERTS ──────────────────────────────────────────────────────────────
  {
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 9.99,
    description: 'Warm fondant with a molten 70% dark chocolate center',
    longDescription: 'A dramatic warm chocolate fondant with a perfectly runny 70% Valrhona center, dusted with cocoa powder and served with a quenelle of vanilla bean ice cream and a drizzle of salted caramel.',
    ingredients: ['Valrhona dark chocolate', 'Butter', 'Eggs', 'Flour', 'Sugar', 'Vanilla ice cream', 'Salted caramel'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-lava-cake.jpg',
    featured: true,
  },
  {
    name: 'Tiramisu',
    category: 'Desserts',
    price: 8.50,
    description: 'Classic Italian tiramisu with mascarpone, espresso and cocoa',
    longDescription: 'Layers of espresso-and-Kahlúa-soaked Savoiardi biscuits and a velvety mascarpone and egg yolk cream, chilled overnight and finished with a fine dusting of premium Valrhona cocoa. Made fresh daily.',
    ingredients: ['Mascarpone', 'Savoiardi', 'Espresso', 'Kahlúa', 'Egg yolks', 'Sugar', 'Valrhona cocoa'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-tiramisu.jpg',
    featured: true,
  },
  {
    name: 'New York Cheesecake',
    category: 'Desserts',
    price: 8.00,
    description: 'Dense baked cheesecake on a graham cracker crust with berry coulis',
    longDescription: 'A dense, tangy New York-style baked cheesecake on a buttery graham cracker base, served with a warm mixed berry coulis and a cloud of fresh whipped cream.',
    ingredients: ['Cream cheese', 'Graham crackers', 'Eggs', 'Sugar', 'Vanilla', 'Butter', 'Mixed berries', 'Whipping cream'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-cheesecake.jpg',
    featured: false,
  },
  {
    name: 'Vanilla Panna Cotta',
    category: 'Desserts',
    price: 7.50,
    description: 'Silky Italian cream dessert with Madagascan vanilla and berry coulis',
    longDescription: 'A silky-smooth Italian set cream infused with Madagascan vanilla beans, gently turned out and served with a vibrant mixed berry coulis, fresh raspberries and a sprig of mint.',
    ingredients: ['Heavy cream', 'Madagascan vanilla', 'Gelatin', 'Sugar', 'Mixed berries', 'Raspberry'],
    allergens: ['Dairy'],
    image: '/uploads/menu-panna-cotta.jpg',
    featured: false,
  },
  {
    name: 'Crème Brûlée',
    category: 'Desserts',
    price: 8.99,
    description: 'Classic French custard with a caramelized sugar crust',
    longDescription: 'A rich vanilla custard baked low and slow in a bain-marie, chilled then finished tableside with a layer of raw sugar caramelized to a thin, glassy toffee crust. Served with seasonal fresh berries.',
    ingredients: ['Heavy cream', 'Egg yolks', 'Sugar', 'Vanilla bean', 'Fresh berries'],
    allergens: ['Dairy', 'Egg'],
    image: '/uploads/menu-panna-cotta.jpg',
    featured: false,
  },
  {
    name: 'Fruit Tart',
    category: 'Desserts',
    price: 7.99,
    description: 'Crispy pastry shell with crème pâtissière and seasonal fruits',
    longDescription: 'A golden sweet shortcrust pastry shell blind-baked until crisp, filled with a silky vanilla crème pâtissière and topped with an array of fresh seasonal fruits and a light apricot glaze.',
    ingredients: ['Shortcrust pastry', 'Milk', 'Egg yolks', 'Sugar', 'Cornstarch', 'Vanilla', 'Seasonal fruits', 'Apricot glaze'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    image: '/uploads/menu-cheesecake.jpg',
    featured: false,
  },
  {
    name: 'Gelato Trio',
    category: 'Desserts',
    price: 7.00,
    description: 'Three scoops of artisan Italian gelato — ask for today\'s flavors',
    longDescription: 'Three generous scoops of house-churned artisan Italian gelato. Ask your server for today\'s flavors, which rotate daily and include classic vanilla bean, rich dark chocolate, pistachio and seasonal fruit sorbets.',
    ingredients: ['Whole milk', 'Cream', 'Sugar', 'Egg yolks', 'Various natural flavors'],
    allergens: ['Dairy', 'Egg', 'Nuts'],
    image: '/uploads/menu-tiramisu.jpg',
    featured: false,
  },

  // ─── BEVERAGES ─────────────────────────────────────────────────────────────
  {
    name: 'Fresh Squeezed Lemonade',
    category: 'Beverages',
    price: 4.50,
    description: 'House-made lemonade with fresh mint and cane sugar',
    longDescription: 'Freshly squeezed lemons sweetened with house-made cane sugar syrup, shaken over ice and garnished with fresh mint leaves, a lemon wheel and a pinch of pink Himalayan salt.',
    ingredients: ['Lemon juice', 'Cane sugar syrup', 'Still water', 'Fresh mint', 'Pink salt'],
    allergens: [],
    image: '/uploads/menu-lemonade.jpg',
    featured: false,
  },
  {
    name: 'Cold Brew Iced Coffee',
    category: 'Beverages',
    price: 5.50,
    description: '18-hour cold brew over ice with choice of whole, oat or almond milk',
    longDescription: 'Our house single-origin cold brew steeped for 18 hours for a smooth, low-acid concentrate, served over ice with your choice of whole, oat or almond milk. Add a flavored syrup for $0.75.',
    ingredients: ['Cold brew coffee', 'Ice', 'Whole/oat/almond milk'],
    allergens: ['Dairy'],
    image: '/uploads/menu-iced-coffee.jpg',
    featured: false,
  },
  {
    name: 'Tropical Mango Smoothie',
    category: 'Beverages',
    price: 6.50,
    description: 'Blended Alphonso mango, pineapple and coconut milk',
    longDescription: 'A thick, tropical blend of ripe Alphonso mango, sweet pineapple chunks and creamy coconut milk, blended smooth with a hint of ginger and lime. Dairy-free and vegan.',
    ingredients: ['Alphonso mango', 'Pineapple', 'Coconut milk', 'Ginger', 'Lime', 'Ice'],
    allergens: [],
    image: '/uploads/menu-smoothie.jpg',
    featured: true,
  },
  {
    name: 'Sparkling Mineral Water',
    category: 'Beverages',
    price: 2.50,
    description: 'San Pellegrino 500ml, served chilled with a lemon wedge',
    longDescription: 'San Pellegrino naturally sparkling mineral water from the Italian Alps, served chilled in the bottle with a fresh lemon wedge.',
    ingredients: ['Sparkling mineral water'],
    allergens: [],
    image: '/uploads/menu-sparkling-water.jpg',
    featured: false,
  },
  {
    name: 'Fresh Orange Juice',
    category: 'Beverages',
    price: 5.00,
    description: 'Freshly squeezed Valencia oranges — served immediately',
    longDescription: 'Pressed to order from Valencia oranges for maximum flavor and vitamins. No concentrates, no additives — just pure, fresh juice. Available in regular (300ml) or large (500ml) sizes.',
    ingredients: ['Valencia oranges'],
    allergens: [],
    image: '/uploads/menu-lemonade.jpg',
    featured: false,
  },
  {
    name: 'Strawberry Milkshake',
    category: 'Beverages',
    price: 7.00,
    description: 'Thick shake with real strawberry and premium vanilla ice cream',
    longDescription: 'A gloriously thick milkshake blended from fresh strawberries, premium vanilla ice cream and whole milk, served in a chilled glass with a wafer straw and a fresh strawberry on the rim.',
    ingredients: ['Fresh strawberries', 'Vanilla ice cream', 'Whole milk'],
    allergens: ['Dairy'],
    image: '/uploads/menu-smoothie.jpg',
    featured: false,
  },
  {
    name: 'Espresso & Specialty Coffee',
    category: 'Beverages',
    price: 3.50,
    description: 'Single / double espresso — ask for cappuccino, latte or flat white',
    longDescription: 'We source our beans from a local specialty roaster. Ask for an espresso, doppio, cappuccino, flat white, oat milk latte or Americano. All made on our La Marzocca machine by trained baristas.',
    ingredients: ['Specialty coffee beans', 'Filtered water', 'Milk (optional)'],
    allergens: ['Dairy'],
    image: '/uploads/menu-iced-coffee.jpg',
    featured: false,
  },
  {
    name: 'Herbal & Premium Teas',
    category: 'Beverages',
    price: 3.00,
    description: 'Selection of loose-leaf teas — English Breakfast, Earl Grey, Mint, Chamomile',
    longDescription: 'Brewed to order using Newby loose-leaf teas in a warmed pot. Choose from English Breakfast, Earl Grey, Moroccan Mint, Chamomile, Green Jasmine or Lemon Ginger. Served with honey and milk.',
    ingredients: ['Premium loose-leaf tea', 'Hot water', 'Honey (optional)', 'Milk (optional)'],
    allergens: ['Dairy'],
    image: '/uploads/menu-sparkling-water.jpg',
    featured: false,
  },
];

async function seedMenu() {
  await mongoose.connect(env.MONGODB_URI);
  console.log('Connected to MongoDB');

  const restaurant = await Restaurant.findOne({ status: 'active' });
  if (!restaurant) {
    console.error('No active restaurant found. Run the main seed first: npx tsx server/scripts/seed.ts');
    await mongoose.disconnect();
    process.exit(1);
  }

  const restaurantId = restaurant._id as mongoose.Types.ObjectId;
  console.log(`Seeding menu for restaurant: "${restaurant.name}" (${restaurantId})`);

  const deletedCats  = await Category.deleteMany({ restaurantId });
  const deletedItems = await MenuItem.deleteMany({ restaurantId });
  console.log(`Cleared ${deletedCats.deletedCount} categories and ${deletedItems.deletedCount} items`);

  const categoryDocs = await Category.insertMany(
    CATEGORIES.map((c) => ({ ...c, restaurantId }))
  );
  console.log(`Created ${categoryDocs.length} categories`);

  const itemDocs = await MenuItem.insertMany(
    MENU_ITEMS.map((item) => ({ ...item, restaurantId }))
  );
  console.log(`Created ${itemDocs.length} menu items`);

  console.log('\nDone! Summary:');
  for (const cat of categoryDocs) {
    const count = itemDocs.filter((i) => i.category === cat.name).length;
    console.log(`  ${cat.name}: ${count} items`);
  }

  await mongoose.disconnect();
}

seedMenu().catch((err) => {
  console.error(err);
  process.exit(1);
});
